Repository Utkarsh1504/DSA-Java, pull requests merged in 2021-09, with the labels that each got.

#3 fixed typo: Assignment
  lessons/assignment.md
Labels: typo

#18 Some changes
  lessons/io-conditionals.md
Labels: ✅ Ready for merge

#16 added bst documentation and add an image
  lessons/images/BinarySearchTree_diagram.png
  lessons/intro-bst.md
Labels: enhancement, java, ✅ Ready for merge
